Smithay/wayland-rs

scanner/src/client_gen.rs
scanner/src/interface_gen.rs
wayland-client/Cargo.toml
wayland-client/src/egl.rs
wayland-client/src/lib.rs
wayland-client/src/wayland.rs
wayland-sys/Cargo.toml
wayland-sys/src/client.rs
wayland-sys/src/common.rs
wayland-sys/src/egl.rs
wayland-sys/src/lib.rs

Add some documentation and finalize the structure of wayland_sys.

Finalize wayland_sys

---

scanner/Cargo.toml
wayland-client/Cargo.toml
wayland-client/build.rs
wayland-sys/Cargo.toml

For uploading their 0.1 on crates.io

Metadata for wayland-sys and wayland-scanner.

---

.travis.yml

Fix GH token

---

scanner/Cargo.toml
scanner/src/client_gen.rs

scanner: Wayland proxies are Send and Sync.

---

protocols/wayland.xml
scanner/Cargo.toml
scanner/src/client_gen.rs
scanner/src/parse.rs
scanner/src/protocol.rs
wayland-client/Cargo.toml
wayland-client/src/lib.rs
wayland-client/src/sys/wayland.rs

Closes #19
Probably made #18 more difficult btw...

Use the bitfield and enum attributes of the new xml file format

---

wayland-client/Cargo.toml
wayland-client/src/lib.rs
wayland-client/wayland.xml
wayland-scanner/src/code_gen.rs
wayland-scanner/src/util.rs
wayland-server/Cargo.toml
wayland-server/src/lib.rs
wayland-server/wayland.xml

Handle enums and bitflags in scanner

---

wayland-client/src/display.rs
wayland-client/src/lib.rs
wayland-scanner/src/code_gen.rs

client: method to query protocol errors

---

wayland-client/build.rs
wayland-scanner/src/lib.rs
wayland-server/build.rs

Docs about how to use the scanner.

Scanner docs

---

wayland-client/examples/simple_client.rs
wayland-client/src/display.rs
wayland-client/src/event_queue.rs
wayland-client/src/lib.rs
wayland-scanner/src/code_gen.rs
wayland-scanner/src/side.rs
wayland-server/src/event_loop.rs
wayland-server/src/lib.rs

Destructor safety machinery

---

wayland-client/Cargo.toml
wayland-client/src/cursor.rs
wayland-client/src/egl.rs
wayland-client/src/lib.rs

`libwayland-egl` and `libwayland-cursor`

client: secondary libs

---

wayland-client/examples/simple_window.rs

This helps make it more obvious whats going on.
Note, could wrap lines here - but didn't since the file is already not strictly 99 width max.

Make width and height variables

---

wayland-client/src/event_queue.rs
wayland-client/src/lib.rs
wayland-scanner/src/code_gen.rs
wayland-server/src/event_loop.rs
wayland-server/src/lib.rs

Very basic mechanism with very low overhead and very small guarantees. The user can they build whatever they want on to of that.

Add a user_data mechanism

---

wayland-client/examples/simple_client.rs
wayland-client/examples/simple_window.rs
wayland-client/src/env.rs
wayland-scanner/src/code_gen.rs

Note: breaking change
Fixes #69

Don't return result when objects are not destroyable.

---

wayland-scanner/src/code_gen.rs
wayland-server/src/lib.rs

To allow the servers to kill offending clients. 🔥

Implement "Ressource::post_error"

---

.travis.yml
book.toml
book/SUMMARY.md
book/chapter_1.md
doc_upload.py
index.html
rust.css

Add a book and the infra to publish it

---

wayland-client/src/lib.rs
wayland-server/src/event_loop.rs
wayland-server/src/lib.rs

I think this is sound for managed objects.
Unmanaged objects should be handled with care, though.

Make client Proxies and server Resources cloneable

---

wayland-server/src/event_loop.rs

#104 did actually not completely fix the logic issue

Fix resource_is_registered

---

wayland-server/src/event_loop.rs

server: fix a memory corruption in global's user_data

---

wayland-sys/src/server.rs

sys: add wl_listener and wl_signal

---

Cargo.toml
tests/basic_global.rs
tests/scanner.rs
tests/scanner_assets/client_code.rs
tests/scanner_assets/interfaces.rs
tests/scanner_assets/protocol.xml
tests/scanner_assets/server_code.rs
wayland-scanner/src/code_gen.rs
wayland-scanner/src/interface_gen.rs
wayland-scanner/src/lib.rs

Add an architecture to test the scanner as well as a dummy protocol file to check its code generation.

Scanner tests

---

book/wayland/p_core/intro.md

Fix broken link

---

wayland-client/src/event_queue.rs
wayland-server/src/event_loop.rs

Allow removal of handlers from event queue/loops

---

wayland-server/src/event_sources.rs

Fixes a possible use-after-free error and the error handling.

Bugfix FdEventSource

---

CHANGELOG.md
tests/dispatch_idle.rs
wayland-server/src/event_loop.rs
wayland-server/src/event_sources.rs
wayland-server/src/lib.rs

server: add idle event sources

---

.travis.yml
tests/helpers/mod.rs

Reverts Smithay/wayland-rs#153
seems like it actually broke everything even though the travis build of the PR succeeded ???

Revert "simplify travis build"

---

.travis.yml
tests/helpers/mod.rs

Reverts Smithay/wayland-rs#154
Apparently the failure where spurious from travis, and not a mistake on our side?

simplify travis build, take 2

---

wayland-protocols/Cargo.toml
wayland-protocols/build.rs
wayland-protocols/misc/server-decoration.xml
wayland-protocols/src/lib.rs
wayland-protocols/src/misc.rs

There is no certaint about when it'll be integrated by wayland-protocols.
Let's have it here in the meantime. It is stable.
cc https://github.com/Smithay/wayland-window/issues/25

Add KDE's decoration protocol

---

Cargo.toml
tests/client_dispatch.rs
tests/client_proxies.rs
tests/server_resources.rs
wayland-client/src/native_lib/proxy.rs
wayland-server/src/rust_imp/resources.rs

Adding yet again more tests, and fixing little bugs found by them.

Add more tests & some bugfixes

---

Cargo.toml
tests/destructors.rs
tests/server_clients.rs
wayland-commons/src/utils.rs
wayland-server/src/client.rs
wayland-server/src/lib.rs
wayland-server/src/native_lib/client.rs
wayland-server/src/rust_imp/clients.rs

Closes #196 
Blocked on https://github.com/Diggsey/lockless/issues/4 or finding an other `AppendList` implementation.

server: rework Client user_data and destructors

---

tests/attach_to_surface.rs
tests/client_proxies.rs
tests/protocol_errors.rs
tests/scanner.rs
tests/server_created_object.rs
tests/server_resources.rs
wayland-client/examples/simple_window.rs
wayland-client/src/globals.rs
wayland-client/src/rust_imp/connection.rs
wayland-client/src/rust_imp/display.rs
wayland-client/src/rust_imp/mod.rs
wayland-client/src/rust_imp/proxy.rs
wayland-commons/examples/manual_global_list.rs
wayland-commons/src/socket.rs
wayland-commons/src/utils.rs
wayland-commons/src/wire.rs
wayland-scanner/src/c_code_gen.rs
wayland-scanner/src/common_gen.rs
wayland-scanner/src/parse.rs
wayland-scanner/src/util.rs
wayland-server/src/native_lib/display.rs
wayland-server/src/rust_imp/clients.rs
wayland-server/src/rust_imp/mod.rs

I noticed #213 recently failed because of formatting, and thought this would be good to do in a separate PR.

Update formatting by re-running latest stable rustfmt

---

tests/attach_to_surface.rs
tests/client_proxies.rs
tests/protocol_errors.rs
tests/scanner.rs
tests/server_created_object.rs
tests/server_global_filter.rs
tests/server_resources.rs
wayland-client/examples/simple_window.rs
wayland-client/src/globals.rs
wayland-client/src/rust_imp/connection.rs
wayland-client/src/rust_imp/display.rs
wayland-client/src/rust_imp/mod.rs
wayland-client/src/rust_imp/proxy.rs
wayland-client/src/rust_imp/queues.rs
wayland-commons/examples/manual_global_list.rs
wayland-commons/src/socket.rs
wayland-commons/src/utils.rs
wayland-commons/src/wire.rs
wayland-scanner/src/c_code_gen.rs
wayland-scanner/src/common_gen.rs
wayland-scanner/src/parse.rs
wayland-scanner/src/protocol.rs
wayland-scanner/src/util.rs
wayland-server/src/native_lib/display.rs
wayland-server/src/rust_imp/clients.rs
wayland-server/src/rust_imp/mod.rs
wayland-sys/Cargo.toml
wayland-sys/src/lib.rs
wayland-sys/src/server.rs

Fix some rustc, clippy warnings

---

.travis.yml
tests/scanner.rs
tests/scanner_assets/c_interfaces.rs
tests/scanner_assets/client_c_code.rs
tests/scanner_assets/client_rust_code.rs
tests/scanner_assets/protocol.xml
tests/scanner_assets/server_c_code.rs
tests/scanner_assets/server_rust_code.rs
wayland-scanner/Cargo.toml
wayland-scanner/src/c_code_gen.rs
wayland-scanner/src/c_interface_gen.rs
wayland-scanner/src/common_gen.rs
wayland-scanner/src/lib.rs
wayland-scanner/src/parse.rs
wayland-scanner/src/protocol.rs
wayland-scanner/src/rust_code_gen.rs
wayland-scanner/src/side.rs
wayland-scanner/src/util.rs

Posting this now to have a travis run for the first converted module and to make it easier to review. The other modules should look similar after conversion.

Use quote for code generation in wayland-scanner

---

CHANGELOG.md
wayland-client/src/display.rs
wayland-client/src/globals.rs
wayland-commons/src/wire.rs

Implement Error for public error types.

---

Cargo.toml
wayland-client/Cargo.toml
wayland-commons/Cargo.toml
wayland-server/Cargo.toml

Signed-off-by: Hal Gentz <zegentzy@protonmail.com>

Bump version of nix.

---

wayland-client/build.rs
wayland-protocols/build.rs
wayland-server/build.rs

Inform cargo of build script file / env var dependencies

---

README.md

https://github.com/Smithay/wayland-rs/issues/276#issuecomment-537425559

Add section about the chatrooms in the readme

---

wayland-client/src/native_lib/proxy.rs
wayland-commons/src/user_data.rs

client: fix the creation of Main<_> in dispatcher so that it is properly attached.

---

wayland-client/examples/simple_window.rs

Doesn't appear to actually make a difference but for the sake of correctness

Fixed copy-paste error in example

---

CHANGELOG.md
wayland-client/src/event_queue.rs
wayland-protocols/src/misc.rs
wayland-protocols/src/stable.rs
wayland-protocols/src/unstable.rs
wayland-protocols/src/wlr.rs
wayland-server/src/rust_imp/globals.rs
wayland-sys/src/server.rs

The docs are saying that you can clone the `QueueToken` however it doesn't implement `Clone` so it's either it shouldn't be cloned and docs must be updated or clone should be added.

client: impl clone for QueueToken

---

CHANGELOG.md
wayland-client/src/proxy.rs

This seems pretty useful tbqh.

client: Add Into<Attached<I: Interface>> impl for Main<I: Interface>

---

CHANGELOG.md
tests/scanner_assets/client_code.rs
tests/scanner_assets/server_code.rs
wayland-client/src/rust_imp/queues.rs
wayland-client/wayland.xml
wayland-server/wayland.xml

Update core protocol to 1.18

---

wayland-client/examples/simple_window.rs

This commit reduce by a lot the time to generate the gradient in simple_window example, and show the good practice to use a buffer to write to a file even temporary.
Testing Wayland on a raspberry pi even on release the generation was taking +4s, now it's take 40 ms, I think it's worth it and doesn't add a lot of code complexity as the gradient generation code is not mean to be important in the simple_window example.
I also added some time information allowing the user to see what take time in the example (where a true use case would probably generate the image way faster using GPU for example). Tell me if you think it's not good to add it.

Use a BufWriter in simple_window example

---

wayland-commons/src/socket.rs

commons: pass MSG_CMSG_CLOEXE to recvmsg

---

CHANGELOG.md
tests/server_clients.rs
wayland-commons/src/socket.rs
wayland-server/src/client.rs
wayland-server/src/lib.rs
wayland-server/src/native_lib/client.rs
wayland-server/src/rust_imp/clients.rs

[server] add wl_client_get_credentials

---

wayland-cursor/src/lib.rs
wayland-egl/src/lib.rs

Also enable the missing docs and missing debug lints

Implement Debug for egl and cursor

---

wayland-backend/src/lib.rs
wayland-backend/src/rs/client/mod.rs
wayland-backend/src/rs/map.rs
wayland-backend/src/rs/server/client.rs
wayland-backend/src/rs/server/common_poll.rs
wayland-backend/src/rs/server/handle.rs
wayland-backend/src/rs/server/mod.rs
wayland-backend/src/rs/server/registry.rs
wayland-backend/src/sys/client/mod.rs
wayland-backend/src/sys/server/mod.rs
wayland-backend/tests/rs_sys_impls.rs
wayland-client/src/cx.rs
wayland-client/src/event_queue.rs
wayland-client/src/globals.rs
wayland-client/src/lib.rs
wayland-server/src/client.rs
wayland-server/src/dispatch.rs
wayland-server/src/display.rs
wayland-server/src/lib.rs
wayland-server/src/socket.rs

Better now than later to do it all.

std::fmt::Debug

---

wayland-client/src/event_queue.rs

This changes the macro to obtain to the delegate using a closure. This allows the user to choose between referencing a field or function to get the delegate.
And documents the associated traits

client: docs for delegating proxy handling

---

wayland-backend/src/rs/client/mod.rs

This makes the rs logic consistent with the sys backend.

backend (rs): dispatch event before marking objects destroyed

---

CHANGELOG.md
wayland-client/src/native_lib/display.rs
wayland-client/src/native_lib/event_queue.rs
wayland-commons/src/wire.rs
wayland-server/src/native_lib/mod.rs

client.native: Don't deref potential nullptr

---

wayland-client/src/event_queue.rs

This is needed to reimplement `WaylandSource` in sctk.

client: add prepare_read and flush to EventQueue

---

wayland-backend/src/rs/server/handle.rs
wayland-backend/src/sys/server/mod.rs
wayland-backend/src/test/protocol_error.rs

backend: allow server to omit ObjectData on error

---

wayland-backend/src/sys/client/mod.rs
wayland-backend/src/sys/server/mod.rs

backend-sys: fix memory leaks

---

.github/workflows/ci.yml
deny.toml

ci: Introduce a cargo-deny workflow

---

wayland-backend/src/sys/server_impl/mod.rs
wayland-sys/CHANGELOG.md
wayland-sys/src/lib.rs

sys: improve trailing comma handling in ffi_dispatch

---

wayland-server/src/dispatch.rs
wayland-server/src/global.rs

I am not sure, if this works exactly in every case, but it appears to be fine? :grimacing:

server: Allow generics in macros

---

wayland-client/src/event_queue.rs
wayland-server/src/dispatch.rs

Some things have changed regarding dispatch, note these changes in the docs.

correct some parts of delegate dispatch

---

wayland-server/src/dispatch.rs
wayland-server/src/global.rs

wayland-server: Properly support generics in dispatch-macros

---

wayland-backend/src/client_api.rs
wayland-backend/src/protocol.rs
wayland-backend/src/rs/client_impl/mod.rs
wayland-backend/src/rs/map.rs
wayland-backend/src/rs/server_impl/client.rs
wayland-backend/src/rs/server_impl/common_poll.rs
wayland-backend/src/rs/server_impl/handle.rs
wayland-backend/src/rs/server_impl/mod.rs
wayland-backend/src/rs/server_impl/registry.rs
wayland-backend/src/rs/socket.rs
wayland-backend/src/rs/wire.rs
wayland-backend/src/server_api.rs
wayland-backend/src/sys/client_impl/mod.rs
wayland-backend/src/sys/mod.rs
wayland-backend/src/sys/server_impl/mod.rs
wayland-backend/src/types/client.rs
wayland-client/src/conn.rs
wayland-client/src/event_queue.rs
wayland-client/src/globals.rs
wayland-client/src/lib.rs
wayland-cursor/src/lib.rs
wayland-egl/src/lib.rs
wayland-server/src/client.rs
wayland-server/src/display.rs
wayland-server/src/socket.rs

hello!
i was looking at the docs for `wayland-server = "0.30.0-beta.1"` and noticed some inconsistent usage of `Self`, so i couldn't help myself and swept through the entire project fixing this. sorry if its a bit too invasive. i broke it up into separate commits to hopefully make it easier.

use the Self type more

---

wayland-client/src/globals.rs

fix typo in globals.rs

---

wayland-backend/CHANGELOG.md
wayland-backend/src/sys/server_impl/mod.rs

backend(sys): make disable_global no-op if the global is already disabled

---

wayland-client/src/lib.rs
wayland-server/CHANGELOG.md
wayland-server/src/client.rs
wayland-server/src/dispatch.rs
wayland-server/src/display.rs
wayland-server/src/global.rs
wayland-server/src/lib.rs
wayland-server/src/socket.rs
wayland-tests/tests/client_connect_to_env.rs

Depends on https://github.com/Smithay/wayland-rs/pull/518

server: documentation

---

wayland-client/src/event_queue.rs

This PR adds support for generics in delegate macros.
Working examples that use the macros are in https://github.com/wash2/client-toolkit

feat: generic delegate macros

---

wayland-protocols-misc/Cargo.toml
wayland-protocols-misc/src/lib.rs

I removed the redundant feature flag :)

Remove redundant feature flag unstable protocols

---

wayland-client/src/conn.rs

client: doc fixup

---

.github/workflows/ci.yml
CHANGELOG.md
Cargo.toml
README.md
wayland-client/Cargo.toml
wayland-commons/Cargo.toml
wayland-commons/src/socket.rs
wayland-cursor/Cargo.toml
wayland-server/Cargo.toml

I fixed #457 for `wayland-*` 0.29 along the way.
Fixes #544.

Update `nix` to 0.24.1

---

wayland-server/CHANGELOG.md
wayland-server/src/client.rs

server: Client is Clone

---

wayland-client/src/event_queue.rs

I've found this very useful and I'm sure others will too.
It's also useful for interfaces that _don't have_ any events, e.g.:
```rust
// These interfaces have no events, so there's nothing to handle.
dispatch_noop!(State: [wl_compositor::WlCompositor]);
dispatch_noop!(State: [ZwlrScreencopyManagerV1]);
dispatch_noop!(State: [wl_subcompositor::WlSubcompositor]);
dispatch_noop!(State: [wl_subsurface::WlSubsurface]);
dispatch_noop!(State: [wp_viewporter::WpViewporter]);
dispatch_noop!(State: [wp_viewport::WpViewport]);
dispatch_noop!(State: [wl_shm_pool::WlShmPool]);
dispatch_noop!(State: [wl_data_device_manager::WlDataDeviceManager]);
```

Add a helper to delegate Dispatch<_> to no-op

---

wayland-scanner/CHANGELOG.md
wayland-scanner/src/common.rs
wayland-scanner/tests/scanner_assets/test-client-code.rs
wayland-scanner/tests/scanner_assets/test-server-code.rs

scanner: generate opcode method on message enums

---

wayland-client/CHANGELOG.md
wayland-client/src/conn.rs
wayland-server/CHANGELOG.md
wayland-server/src/socket.rs

Align our behavior on libwayland regarding env variables

---

wayland-backend/src/sys/server_impl/mod.rs

backend: server-sys: set PENDING_DESTRUCTORS when killing a client

---

wayland-backend/src/protocol.rs
wayland-client/src/event_queue.rs
wayland-client/src/globals.rs
wayland-client/src/lib.rs
wayland-tests/Cargo.toml
wayland-tests/tests/client_globals_helpers.rs
wayland-tests/tests/globals.rs

Based on #551 but allows for both initial global list and handling of dynamic globals
cc @i509VCB

client: introduce globals init helpers

---

wayland-protocols/CHANGELOG.md
wayland-protocols/src/wp.rs
wayland-server/src/socket.rs

this adds a new staging protocol: fractional-scale-v1

protocols: bump to wayland-protocols 1.31

---

wayland-scanner/Cargo.toml
wayland-scanner/src/parse.rs

Fixes https://github.com/Smithay/wayland-rs/issues/606.

scanner: Update `quick-xml` to latest release

---

wayland-client/examples/simple_window.rs

Sets a cleaner example for others to follow.

Use delegate_noop! in examples

---

wayland-backend/src/rs/server_impl/common_poll.rs
wayland-backend/src/rs/server_impl/handle.rs
wayland-backend/src/rs/socket.rs

Dubiously useful, but doesn't take much, and it's a useful reference point for portability to different Unix systems.

Add support for compiling on macOS

---

wayland-cursor/src/lib.rs

fix: doc is not shown for `set_fallback` api

---

wayland-scanner/Cargo.toml
wayland-scanner/src/parse.rs

Just like https://github.com/Smithay/wayland-rs/pull/674.

scanner: Update ˙quick-xml`

---

wayland-scanner/Cargo.toml

There were two new releases shortly after https://github.com/Smithay/wayland-rs/pull/736.

scanner: Update `quick-xml` to `v0.34`

---

wayland-backend/CHANGELOG.md
wayland-backend/Cargo.toml
wayland-client/Cargo.toml
wayland-cursor/Cargo.toml
wayland-egl/Cargo.toml
wayland-protocols-misc/Cargo.toml
wayland-protocols-plasma/Cargo.toml
wayland-protocols-wlr/Cargo.toml
wayland-protocols/Cargo.toml
wayland-scanner/CHANGELOG.md
wayland-scanner/Cargo.toml
wayland-server/Cargo.toml
wayland-sys/Cargo.toml
wayland-tests/Cargo.toml

`cargo release --no-publish --no-tag --no-push --execute patch`
If CI passes, I can then merge and tag this, so it will be released on crates.io.

Bump versions and update changelogs

---

wayland-scanner/CHANGELOG.md
wayland-scanner/Cargo.toml

Just like https://github.com/Smithay/wayland-rs/pull/749, this time for https://github.com/ruffle-rs/ruffle/pull/18414.

Update `quick-xml` to 0.37

---

.cirrus.yml
.github/workflows/ci.yml
wayland-protocols/CHANGELOG.md
wayland-protocols/src/wp.rs

Update to wayland-protocols 1.41

---

wayland-protocols/CHANGELOG.md
wayland-protocols/src/wp.rs

Adds `color-representation-v1` protocol.

protocols: Update to wayland-protocols 1.44

---

wayland-backend/CHANGELOG.md
wayland-backend/src/sys/client_impl/mod.rs

This reverts commit d309063eecbd0d6671455500a5749f2a3c3f44dc.
Fixes #809.

Revert "backend: hold the dispatch lock for send_request"

---

wayland-backend/CHANGELOG.md
wayland-backend/Cargo.toml
wayland-client/Cargo.toml
wayland-cursor/Cargo.toml
wayland-egl/Cargo.toml
wayland-protocols-misc/Cargo.toml
wayland-protocols-plasma/Cargo.toml
wayland-protocols-wlr/Cargo.toml
wayland-protocols/Cargo.toml
wayland-server/Cargo.toml
wayland-tests/Cargo.toml

Patch release to fix https://github.com/Smithay/wayland-rs/issues/809.

chore: Release

---

wayland-backend/src/client_api.rs
wayland-backend/src/debug.rs
wayland-backend/src/protocol.rs
wayland-backend/src/rs/client_impl/mod.rs
wayland-backend/src/rs/server_impl/client.rs
wayland-backend/src/rs/server_impl/common_poll.rs
wayland-backend/src/rs/server_impl/mod.rs
wayland-backend/src/rs/wire.rs
wayland-backend/src/sys/client_impl/mod.rs
wayland-backend/src/sys/server_impl/mod.rs
wayland-backend/src/types/client.rs
wayland-scanner/src/client_gen.rs
wayland-scanner/src/parse.rs
wayland-scanner/src/server_gen.rs
wayland-scanner/src/token.rs
wayland-scanner/src/util.rs
wayland-server/src/dispatch.rs
wayland-server/src/socket.rs
wayland-sys/src/common.rs

Run `cargo +nightly clippy --fix`, then again with `--features client_system,server_system`.

Fix nightly clippy lints
