- wayland-sys/Cargo.toml
- wayland-sys/src/client.rs
- wayland-sys/src/common.rs
- wayland-sys/src/egl.rs
- wayland-sys/src/lib.rs
And reexport the C types used by the library, to future-proof things.
> wl-sys: Update to libc-0.2 and dlib-0.2.

- scanner/src/client_gen.rs
- scanner/src/interface_gen.rs
- wayland-client/src/egl.rs
- wayland-sys/Cargo.toml
- wayland-sys/src/client.rs
- wayland-sys/src/common.rs
- wayland-sys/src/cursor.rs
- wayland-sys/src/egl.rs
- wayland-sys/src/lib.rs
- wayland-sys/src/server.rs
cc #41 
might be a breaking change, could be the occasion to squeeze in the few other planned and release `0.6`
> Move out of libc in profit of std::os::raw

- .travis.yml
- README.md
- protocols/unstable/xdg-shell-unstable-v5.xml
- protocols/wayland.xml
- scanner/Cargo.toml
- wayland-client/Cargo.toml
- wayland-client/build.rs
- wayland-client/src/events.rs
- wayland-client/src/lib.rs
- wayland-client/src/sys/mod.rs
- wayland-client/src/sys/xdg_shell.rs
- wayland-client/src/wayland.rs
- wayland-client/src/xdg_shell.rs
- wayland-sys/Cargo.toml
Creates the infrastructure for supporting other protocols and introduce the first unstable protocol: `xdg_shell`.
Closes #29 and #30.
> Add support for xdg_shell

- wayland-server/src/event_loop.rs
There is a typo in declare_handler! macro. This PR fixed it.
> fix typo for declare_handler! macro

- wayland-client/src/event_queue.rs
- wayland-client/src/lib.rs
- wayland-protocols/src/protocol_macro.rs
- wayland-scanner/src/code_gen.rs
- wayland-server/src/event_loop.rs
- wayland-server/src/lib.rs
- wayland-sys/src/lib.rs
This implements a safety mechanism regarding foreign wayland objects and `user_data`:
When wrapping a wayland object, we try to recognize a magic pointer we stored in its implementation (that we don't use because we have a custom dispatcher). If this pointer is not there, this means this object is not ours, and we act conservatively and don't try to read its user_data or manage it in any way.
> User data safety

- wayland-client/src/lib.rs
Speaks for itself; I wanted to use `debug!("stuff : {:?}")` on a `RequestResult` to have it nicely in my logs. Turns out a fmt::Debug impl was missing.
> Add fmt::Debug trait for RequestResult

- wayland-server/src/event_loop.rs
I find the resource_is_registered function do not work as it expected.
* If the resource is registered by EventLoop.register api, the result of calling resource_is_register will be false.
* If the resource is registered by EventLoop.register_with_destructor, the result of calling resource_is_register will be true.
So I make this pull request to fix it. Here are a few things I have done.
* Fix the  resource_is_registered 
```
ffi_dispatch!(
WAYLAND_SERVER_HANDLE,
wl_resource_instance_of,
resource.ptr(),
R::interface_ptr(),
h as *const _ as *const c_void
)
```
to 
```
ffi_dispatch!(
WAYLAND_SERVER_HANDLE,
wl_resource_instance_of,
resource.ptr(),
R::interface_ptr(),
&RUST_MANAGED as *const _ as *const _
)
```
* Re-implement register by calling register_with_destructor because of their …
> Rework resource_is_registered function

- .travis.yml
- Cargo.toml
- tests/helpers/mod.rs
- tests/skel.rs
- wayland-protocols/Cargo.toml
Basic test infrastructure for the set of libs.
Client & Server libs need to be tested together, so we cannot really unit-test them. Luckily cargo supports packages composed entirely of tests, so the root of the workspace will host them. 😄 
I'll add some tests before merging.
> Test infrastructure

- .gitignore
- .travis.yml
- tests/attach_null_to_surface.rs
- tests/helpers/mod.rs
- wayland-client/examples/simple_window.rs
- wayland-client/src/cursor.rs
- wayland-client/src/display.rs
- wayland-client/src/egl.rs
- wayland-client/src/env.rs
- wayland-client/src/event_queue.rs
- wayland-client/src/lib.rs
- wayland-protocols/build.rs
- wayland-protocols/src/stable.rs
- wayland-protocols/src/unstable.rs
- wayland-scanner/src/code_gen.rs
- wayland-scanner/src/interface_gen.rs
- wayland-scanner/src/parse.rs
- wayland-scanner/src/protocol.rs
- wayland-scanner/src/side.rs
- wayland-scanner/src/util.rs
- wayland-server/src/display.rs
- wayland-server/src/event_loop.rs
- wayland-server/src/event_sources.rs
- wayland-server/src/lib.rs
- wayland-sys/src/client.rs
- wayland-sys/src/server.rs
- `cargo test --all` in travis
- Fixes #118 
- Add the ability to use `declare_handler!()` macro and its friends on types with type parameters to make generic implementations (this will help remove some cryptic unsafe impls from downstream crates)
> Usability changes

- wayland-server/src/event_loop.rs
> server: document blocking behavior of EventLoop::run()

- wayland-sys/src/client.rs
- wayland-sys/src/server.rs
Debug messages about missing symbols will now only be
displayed if the env variable WAYLAND_RS_DEBUG is set.
(the actual value does not matter)
Fixes #127
> sys: hide debug messages behind env variable

- wayland-sys/src/client.rs
- wayland-sys/src/server.rs
This adds a maintenance overhead of making sure the listed
`libwayland-{client, server}.so` versions are correct for our current
target unfortunately but should also be completely backwards compatible
as it will still try the "bare" version first and only try the others if
it can not find that one.
Fixes #139
> Added a workaround when using dlopen on Ubuntu 17.04

- .travis.yml
- README.md
- tests/scanner_assets/client_code.rs
- tests/scanner_assets/protocol.xml
- tests/scanner_assets/server_code.rs
- wayland-client/Cargo.toml
- wayland-protocols/Cargo.toml
- wayland-scanner/src/code_gen.rs
- wayland-scanner/src/parse.rs
- wayland-server/Cargo.toml
- wayland-server/src/event_sources.rs
- wayland-server/src/lib.rs
- wayland-sys/Cargo.toml
Updates dependencies:
- dlib -> 0.4
- bitflags -> 1.0 [breaking change]
And correct documentation for enum & bitflags variants that were not always properly generated.
Also, document that the last supported rust version is 1.20 and CI-test it.
> [breaking] Update deps & fix documentation of enum/bitflags variants

- CHANGELOG.md
- wayland-client/Cargo.toml
- wayland-client/src/env.rs
- wayland-client/src/event_queue.rs
- wayland-client/src/lib.rs
- wayland-server/Cargo.toml
- wayland-server/src/event_loop.rs
- wayland-server/src/lib.rs
- [client] Add `EnvHandler::init_with_notify()` to still be notified about global events when using `EnvHandler`.
- [client/server] Externalise state logic to crate `token_store`
> Add a notify to EnvHandler & externalize state to token_store

- wayland-scanner/src/parse.rs
Fixes an issue found while parsing the KDE client side decoration protocol where parsing the copyright clause would cause a panic if it contained a CDATA instead of a just the contents of the copyright notice.
This fixes this by properly unwrapping the string from the `CData`
> Fixes #158 Can now parse KDE server dec protocol

- CHANGELOG.md
- wayland-client/src/display.rs
Check if the client libraries are available in
`Display::connect_to_env` before accessing `WAYLAND_CLIENT_HANDLE`.
This should help with https://github.com/tomaka/winit/issues/504.
> client: check libs in `Display::connect_to_env`

- CHANGELOG.md
- wayland-client/src/display.rs
- wayland-client/src/proxy.rs
- wayland-protocols/src/protocol_macro.rs
- Allows the use of a foreign `wl_display`
- Expose generated C interfaces for protocols
Fixes #171 
Fixes #172 
@myfreeweb Can you confirm this meets your needs?
> Improvements to C interop client-side

- CHANGELOG.md
- wayland-scanner/src/c_code_gen.rs
Was erroring with "expected mut or const in raw pointer type"
> scanner: Fix '*mut_' typo (add space)

- wayland-client/src/proxy.rs
This allows you to use functions which depend on the PartialEq and Eq trait being defined.
Fixes #181
> Proxy::equals -> PartialEq::eq, impl Eq for Proxy

- CHANGELOG.md
- tests/attach_to_surface.rs
- tests/client_dispatch.rs
- tests/client_proxies.rs
- tests/destructors.rs
- tests/globals.rs
- tests/helpers/mod.rs
- tests/server_created_object.rs
- tests/server_resources.rs
- wayland-client/examples/dynamic_globals.rs
- wayland-client/examples/simple_window.rs
- wayland-client/src/globals.rs
- wayland-client/src/native_lib/proxy.rs
- wayland-client/src/proxy.rs
- wayland-client/src/rust_imp/display.rs
- wayland-client/src/rust_imp/proxy.rs
- wayland-client/src/rust_imp/queues.rs
- wayland-commons/src/lib.rs
- wayland-commons/src/utils.rs
- wayland-server/src/native_lib/resource.rs
- wayland-server/src/resource.rs
- wayland-server/src/rust_imp/clients.rs
- wayland-server/src/rust_imp/resources.rs
cc #196 
This changes the user data mechanism to be the following:
- the user data of a wayland object is set once and for all at implementation time
- it can be accessed from any handle via a type `user_data<UD>(&self) -> Option<&UD>` method which is a thin wrapper around `Box<Any>::downcast_ref()`
- the user is responsible for integrating interior mutability to the type if they want
In particular, the previous behavior can be reached by using an `AtomicPtr` as the `UD` type, but it makes the default behavior much more safe.
What do you think of this, @Drakulix ?
> Rework Proxy&Resource user_data mechanism

- .travis.yml
- travis_install_wayland.sh
This avoids rebuilding them every run of the CI, speeding things up.
Fixes #188.
> travis: cache the wayland libs

- .travis.yml
- CHANGELOG.md
- Cargo.toml
- README.md
- tests/globals.rs
- tests/helpers/mod.rs
- tests/server_global_filter.rs
- wayland-server/src/display.rs
- wayland-server/src/native_lib/display.rs
- wayland-server/src/native_lib/globals.rs
- wayland-server/src/rust_imp/display.rs
- wayland-server/src/rust_imp/globals.rs
- wayland-sys/src/server.rs
When creating a global, it is possible to associate a closure to it
that can be used to filter which clients are allowed to see the
existence of this global.
This bumps the minimal version of the wayland libs to 1.13.0.
Fixes #168
> server: implement global filtering capabilities

- CHANGELOG.md
- tests/server_created_object.rs
- wayland-commons/src/map.rs
Client ids start at 1 and server ids start at SERVER_ID_LIMIT, not
SERVER_ID_LIMIT+1.
cc #224
> commons: fix server ids handling in map

- CHANGELOG.md
- tests/attach_to_surface.rs
- tests/client_proxies.rs
- tests/destructors.rs
- tests/globals.rs
- tests/scanner_assets/client_c_code.rs
- tests/scanner_assets/client_rust_code.rs
- tests/scanner_assets/server_c_code.rs
- tests/scanner_assets/server_rust_code.rs
- tests/server_clients.rs
- tests/server_created_object.rs
- tests/server_global_filter.rs
- tests/server_resources.rs
- wayland-client/examples/dynamic_globals.rs
- wayland-client/examples/simple_window.rs
- wayland-client/src/globals.rs
- wayland-client/src/lib.rs
- wayland-client/src/proxy.rs
- wayland-protocols/src/protocol_macro.rs
- wayland-scanner/src/c_code_gen.rs
- wayland-scanner/src/common_gen.rs
- wayland-scanner/src/rust_code_gen.rs
- wayland-server/src/lib.rs
- wayland-server/src/native_lib/display.rs
- wayland-server/src/resource.rs
- wayland-server/src/rust_imp/clients.rs
As discussed in #228 (PoC v2 + `implement_closure()` + `implement_dummy()`).
Implemented client- and server-side.
Additionally I changed the `dynamic_globals` example to use trait-based event handling for `wl_output` as I thought it was a good place where the closure implementation was rather complex with lots of enum cases.
> Trait-based event handling

- CHANGELOG.md
- tests/client_dispatch.rs
- tests/client_proxies.rs
- tests/helpers/mod.rs
- tests/send_sync.rs
- tests/server_resources.rs
- wayland-client/src/globals.rs
- wayland-client/src/native_lib/proxy.rs
- wayland-client/src/proxy.rs
- wayland-client/src/rust_imp/proxy.rs
- wayland-server/src/display.rs
- wayland-server/src/lib.rs
- wayland-server/src/native_lib/resource.rs
- wayland-server/src/resource.rs
- wayland-server/src/rust_imp/clients.rs
- wayland-server/src/rust_imp/resources.rs
The implementation methods are now `.implement()` which allows
non-`Send` implementations and panics if called from the wrong
thread, and `.implement_threadsafe()` which accepts only `Send`
implementations and can be called from any thread.
This is accompanied by removing any `Send` / `Sync` implementations
server-side when the `native_lib` feature is activated, as the
C library actually is never threadsafe (contrarily to the client
one).
> client+server: make non-send impls the default

- CHANGELOG.md
- wayland-commons/src/socket.rs
Fixes #235 
@YaLTeR can you confirm this fixes the issue ?
> commons: close fds we dup-ed after sending them

- CHANGELOG.md
- wayland-client/examples/simple_window.rs
- wayland-client/src/lib.rs
- wayland-client/src/sinks.rs
- wayland-commons/src/lib.rs
- wayland-commons/src/sinks.rs
This is the last outstanding point of #228 , this allows downstream users to opt-in to an iterator-based event handling for some of their Wayland objects.
Also introduces an adapter in wayland-client that links an event iterator to an event queue, so that it will block on it if there are no pending events.
> Introduce event iterators & sinks

- CHANGELOG.md
- wayland-client/src/globals.rs
- drop the `Send` bounds,
- fix the warning in `global_filter!()`.
> GlobalManager updates

- CHANGELOG.md
- tests/attach_to_surface.rs
- tests/client_proxies.rs
- tests/destructors.rs
- tests/globals.rs
- tests/scanner.rs
- tests/scanner_assets/client_c_code.rs
- tests/scanner_assets/client_rust_code.rs
- tests/scanner_assets/server_c_code.rs
- tests/scanner_assets/server_rust_code.rs
- tests/server_clients.rs
- tests/server_created_object.rs
- tests/server_resources.rs
- wayland-client/examples/dynamic_globals.rs
- wayland-client/examples/simple_window.rs
- wayland-client/src/globals.rs
- wayland-client/src/native_lib/proxy.rs
- wayland-client/src/proxy.rs
- wayland-client/src/rust_imp/display.rs
- wayland-client/src/rust_imp/mod.rs
- wayland-client/src/rust_imp/queues.rs
- wayland-commons/src/lib.rs
- wayland-scanner/src/c_code_gen.rs
- wayland-scanner/src/common_gen.rs
- wayland-scanner/src/protocol.rs
- wayland-server/src/resource.rs
- wayland-server/src/rust_imp/clients.rs
- wayland-server/src/rust_imp/mod.rs
- Future-proof protocol enums by adding a `#[doc(hidden)] __nonexhaustive` variant. Should be migrated to https://github.com/rust-lang/rust/issues/44109 once it is stabilized. This makes updating the protocols a non-breaking change.
- Remove `GlobalManager::instantiate_auto` which was way too error prone, and replace it with `GlobalManager::instanciate_range`. Also improve the docs regarding to interface versioning.
- Actually check that the versions of messages sent and received over the wire are correct wrt to their supported version, and trigger protocol errors if they aren't (as the C lib does).
> Future proof protocol updates

- .travis.yml
- Cargo.toml
- tests/client_dispatch.rs
- tests/client_proxies.rs
- tests/server_resources.rs
tarpaulin can now again be compiled on stable, and when run on stable it
does not yet show the multithreading bug.
see https://github.com/xd009642/tarpaulin/issues/190#issuecomment-460054663
> travis: run tarpaulin on stable

- CHANGELOG.md
- tests/client_connect_to_env.rs
- wayland-client/src/display.rs
The fallback to `wayland-0` if `WAYLAND_DISPLAY` is not set is a legacy practice that should no longer be followed, as it can cause clients to connect to the wrong compositor, and all compositors should set up the environment correctly.
> client: don't fallback on wayland-0 at connect time

- CHANGELOG.md
- wayland-client/src/display.rs
There was no real reason to prevent client-side `Display` from being clone.
> client: Display is Clone

- CHANGELOG.md
- tests/scanner.rs
- wayland-client/build.rs
- wayland-protocols/build.rs
- wayland-scanner/src/lib.rs
- wayland-scanner/src/parse.rs
- wayland-server/build.rs
This moves the logic of specifying destructor events out of wayland-scanner, as my initial assumption that `wl_callback.done` would be the only ever destructor event turned out to be wrong.
> scanner: allow configuration of destructor events

- Cargo.toml
- wayland-client/Cargo.toml
- wayland-client/src/rust_imp/queues.rs
- wayland-commons/Cargo.toml
- wayland-commons/src/lib.rs
- wayland-commons/src/socket.rs
- wayland-server/Cargo.toml
This should probably be handled as a follow-up to https://github.com/Smithay/calloop/pull/6.
Once that is merged, I can update this to completely get rid of nix 0.13.
> Update to nix 0.14.1

- CHANGELOG.md
- wayland-client/src/proxy.rs
- wayland-server/src/resource.rs
Since `|_, _| ()` and `()` are both `Send`, I see no reasons why `Proxy::implement_dummy` shouldn't use `implement_closure_threadsafe` instead of `implement_closure`.
> Set Proxy::implement_dummy threadsafe

- CHANGELOG.md
- wayland-client/src/proxy.rs
- wayland-server/src/resource.rs
This follows #269.
I've introduced new implementation functions in `NewProxy` and `NewResource` to be able
to mix thread unsafe implementations with threadsafe user data.
To keep it consistent, it comes in two flavors: `implement` and `implement_closure`. I've also modified the documentation of the non-threadsafe functions, I hope it's ok.
> Add `implement*_user_data_threadsafe()` functions

- wayland-client/src/display.rs
- wayland-client/src/globals.rs
- wayland-commons/src/wire.rs
- wayland-protocols/build.rs
* Abolish deprecated method `description` of `::std::error::Error.`
* Factorize complex type into `type` definitions in `wayland-protocols/build.rs`
> Resolve clippy warnings

- CHANGELOG.md
- README.md
- tests/client_proxies.rs
- wayland-client/src/display.rs
- wayland-client/src/native_lib/display.rs
- wayland-client/src/native_lib/proxy.rs
- wayland-commons/src/wire.rs
When attempting to send a message from a proxy and using the `use_system_lib`, check if the associated `Display` is actually still alive before calling into FFI. If not, behave as a dead proxy.
This should fix a number of crashes associated to destructors and final cleanups in apps, when a component than sends wayland requests from its destructor happened to be dropped after the display.
> client: track display lifetime in proxies

- CHANGELOG.md
- wayland-cursor/Cargo.toml
- wayland-cursor/src/lib.rs
~~This PR inserts a Rust implementation into the wayland-cursor crate, but allowing to fallback to the system wayland-cursor.so, for interoperability with other libraries.
The rust implementation is backwards compatible for the most part (except for some lifetimes that aren't needed anymore).~~
This PR reimplements in Rust the `wayland-cursor` crate. The API is changed to be hopefully more Rust-y, since we don't have the c library to follow anymore.
> [WIP] Make the `cursor` feature full rust

- wayland-cursor/Cargo.toml
- wayland-cursor/src/lib.rs
The `xcur` crate had some bugs, so here is a new implementation which (hopefully) fixes them.
@vberger
> Remove dependency on xcur

- wayland-client/LICENSE.txt
- wayland-client/README.txt
- wayland-commons/LICENSE.txt
- wayland-commons/README.txt
- wayland-cursor/LICENSE.txt
- wayland-cursor/README.txt
- wayland-egl/LICENSE.txt
- wayland-egl/README.txt
- wayland-protocols/LICENSE.txt
- wayland-protocols/README.txt
- wayland-scanner/LICENSE.txt
- wayland-scanner/README.txt
- wayland-server/LICENSE.txt
- wayland-server/README.txt
- wayland-sys/LICENSE.txt
- wayland-sys/README.txt
To make it easier for Linux distributions, ship the license text within
each crate directory.
Also add a stub README pointing them to the relevant docs.rs page.
Signed-off-by: Michel Alexandre Salim <michel@michel-slm.name>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/smithay/wayland-rs/323)
> Add per-crate license and stub documentation

- CHANGELOG.md
- tests/scanner_assets/client_code.rs
- tests/scanner_assets/server_code.rs
- wayland-client/src/lib.rs
- wayland-client/src/proxy.rs
- wayland-cursor/rustfmt.toml
- wayland-scanner/src/common_gen.rs
- wayland-server/src/lib.rs
- wayland-server/src/resource.rs
Implement std::fmt::Debug on various server and client core wrappers and
and so make Event/Request to derive std::fmt::Debug impl.
Fixes #311.
> client: server: scanner: Make crate more debuggable

- wayland-scanner/src/parse.rs
See https://gitlab.freedesktop.org/wayland/wayland/-/merge_requests/82.
Once protocol files are updated, this will remove the need for workarounds to specify these separately.
> scanner: parse event type from xml

- wayland-client/Cargo.toml
- wayland-client/examples/simple_window.rs
As of Rust 1.32, there is a method in the standard library to convert a u32 to a native endian byte slice. This PR takes advantage of this method to remove the dependency on the `byteorder` crate for the `simple-window` example.
> remove byteorder dependency for wayland-client example

- wayland-client/examples/simple_window.rs
This follows #336 further modernizing the `simple_window` example. 
* remove `extern crate`
* remove `macro_use`
* nested `use` statements
* replace unwraps with `?` by returning `Result` from `main`
* correct or allow all clippy lints
Let me know if there is anything you don't like in here. I also tried to update/extend the comments, but my wayland knowledge is minimal so there wasn't much I could do there. I'd be happy to do this for the remaining examples if there is interest in that.
> modernize simple_window example

- CHANGELOG.md
- tests/client_proxies.rs
- tests/helpers/mod.rs
- wayland-client/src/native_lib/mod.rs
- wayland-client/src/rust_imp/mod.rs
- wayland-client/src/rust_imp/proxy.rs
- wayland-commons/src/lib.rs
- wayland-scanner/src/common_gen.rs
When we receive an event with a non-nullable object argument which
points to a non-existing object, summon a dead object to replace it
rather than crashing.
This can happen if we destroyed the target object conccurently with the
server sending us this event, and we should not crash due to that.
Fixes #334
> client: Summon dead Proxies for dead arguments

- CHANGELOG.md
- wayland-client/src/rust_imp/connection.rs
Overwise the event is queued like any other, the  next read triggers a broken pipe, and only that last error is reported to the user.
> client: early return parsing when encountering a protocol error

- wayland-client/Cargo.toml
- wayland-client/examples/simple_window.rs
This updates the simple window example to use xdg protocol.
Tested on Fedora 33 and TinyWL.
Resolves https://github.com/Smithay/wayland-rs/issues/315
> simple window xdg

- CHANGELOG.md
- wayland-client/src/display.rs
Since we are either taking ownership of the socket or closing it at this point,
we should not retain the environment variable as it will only confuse child
processes.
> Unset WAYLAND_SOCKET when we use the socket

- .github/workflows/ci.yml
- CHANGELOG.md
- wayland-client/src/native_lib/proxy.rs
This ensures that the user_data associated with a proxy is
correctly cleaned up when sending a destructor request.
Also, the dispatch logic was updated to correctly handle the case where
an object is destroyed from within its own dispatch closure.
Fixes #358
> client: proper cleanup on send on system impl

- tests/protocol_errors.rs
- wayland-commons/src/socket.rs
If there is nothing to send, there's no point actually making the system call.
The list of FDs is not checked because sending FDs without also sending data is
not permitted anyway.
> wayland-commons: avoid empty sendmsg on flush

- wayland-commons/Cargo.toml
- wayland-cursor/Cargo.toml
- wayland-scanner/Cargo.toml
- wayland-server/Cargo.toml
- wayland-sys/Cargo.toml
Some dependencies seems outdated, and does not compile with rustc 1.49.0.
This pull request bumps some dependencies in order to all crates compile with minimal dependency versions.
You can generate `Cargo.lock` with minimal dependency versions by `cargo +nightly update -Z minimal-versions`.
(Once `Cargo.lock` is generated, build and test can be proceeded by stable rustc.)
This PR chose literally minimum compilable deps versions to minimize unexpected side effects, but it results in compiler warnings in some crates (for example, `lazy-static v1.0.2` uses `std::sync::ONCE_INIT` internally, [which is now deprecated](https://doc.rust-lang.org/stable/std/sync/constant.ONCE_INIT.html)).
I think some dependencies should be updated to more recent versions, but it is out of scope of this PR.
> Make crates buildable with minimal dependency versions

- CHANGELOG.md
- Cargo.toml
- README.md
- wayland-client/Cargo.toml
- wayland-server/Cargo.toml
- wayland-server/README.md
- wayland-sys/Cargo.toml
- wayland-sys/src/client.rs
- wayland-sys/src/cursor.rs
- wayland-sys/src/egl.rs
- wayland-sys/src/server.rs
This upgrades wayland-sys' dlib dependency to the new release. Now the dlopen feature won't interfere with other crates using dlib. I have tested this with the `dlopen` feature enabled and disabled on smithay-client-toolkit.
> Upgrade to dlib 0.5

- CHANGELOG.md
- wayland-client/src/lib.rs
- wayland-server/src/lib.rs
Hi,
with some help from the matrix chat, i have added with this tiny change the possibility to use attributes  for `request_enum!` and `event_enum!` macros. The attributes can be added just before the enum name, for example:
```rust
request_enum!(
#[derive(Debug)]WaylandRequest |
Compositor => WlCompositor,
Subcompositor => WlSubcompositor,
Shm => WlShm,
Seat => WlSeat
);
```
The macro will copy everything inside `#[...]`, so it will works also for all the the attributes. 
Thanks for the attention and for the effort involved into the project!
> Added to `request_enum` and `event_enum` the possibility to handle attributes

- CHANGELOG.md
layer-shell version 4 introduces a new keyboard interactivity enum.
---
Unfortunately this is truly API breaking…
> Update wlr-protocols (layer-shell version 4)

- CHANGELOG.md
- wayland-client/src/lib.rs
Using the `crate::` modifier allows users to invoke this macro with no
`use` import, e.g.
wayland_client::event_enum! { ... }
> client: Fix not found macro

- CHANGELOG.md
- wayland-server/src/client.rs
- wayland-server/src/native_lib/client.rs
- wayland-server/src/rust_imp/clients.rs
Hi,
this little patch add `PartialEq` implementation for the `Client` structure by just using the already implemented `equals` function. Implementing `PartialEq` allow to integrate `Client` with other standard rust components that rely on that trait.
Thanks for the attention,
Have a good day
> Added `PartialEq` implementation for the `Client` structure.

- CHANGELOG.md
- wayland-protocols/Cargo.toml
- wayland-protocols/README.md
- wayland-protocols/build.rs
- wayland-protocols/src/lib.rs
- wayland-protocols/src/protocol_macro.rs
- wayland-protocols/src/staging.rs
- wayland-protocols/src/unstable.rs
Updates wayland-protocols to 1.21.
This also adds a module and feature to enable `staging` modules.
> protocols: update to 1.21

- wayland-protocols/src/lib.rs
The free desktop gitlab is probably the preferred link nowadays.
> protocols: use gitlab fdo link for wayland-protocols

- wayland-backend/src/protocol.rs
- wayland-client/src/event_queue.rs
DataInit has made this bound redundant.
> client: remove unneeded Default bound for DelegateDispatch::UserData

- wayland-client/src/conn.rs
- wayland-client/src/lib.rs
This wasn't public, so an error enum could not contain this.
> client: export ConnectError

- wayland-backend/CHANGELOG.md
- wayland-backend/src/sys/server/mod.rs
This was something not carried over from the previous 0.29.x series of the library.
> backend-server: readd forgotten wl_display_destroy

- wayland-egl/src/lib.rs
`WlEglSurface` is not Sync because the inner pointer from libwayland-egl performs no internal synchronization. Meaning a `Mutex<WlEglSurface>` is needed for `Sync` to be satisfied.
This pull request also justifies why `WlEglSurface` is send and adds a safety comment.
> wayland-egl: remove unsafe Sync impl

- wayland-backend/CHANGELOG.md
- wayland-backend/src/rs/client/mod.rs
> backend.rs.client: debug-print of wl_display events

- wayland-backend/build.rs
Path of `rerun-if-changed` was not updated after file structure was updated, it resulted in cache being always invalid and thus causing Smithay (and probably SCTL as well) to recompile the whole wayland-rs on every cargo check.
I would appreciate an alpha-9 release with this fix, in order to bring development experience of Smithay back to normal.
> wayland.backend: Fix build.rs cache

- wayland-client/src/conn.rs
- wayland-client/src/event_queue.rs
- wayland-server/src/dispatch.rs
- wayland-server/src/display.rs
- wayland-server/src/global.rs
In order to create a resource in wayland-server using some `ObjectData` implementation, the underlying handle needs to be exposed.
The client is also made available for consistency.
> client & server: Expose underling `Handle` types

- wayland-client/examples/list_globals.rs
- wayland-client/src/conn.rs
- wayland-client/src/event_queue.rs
Pretty much a copy of `Connection::roundtrip` for `EventQueue`
> client: add EventQueue::sync_roundtrip

- wayland-client/examples/list_globals.rs
- wayland-client/examples/simple_window.rs
- wayland-client/src/event_queue.rs
- wayland-client/src/globals.rs
- wayland-client/src/lib.rs
- wayland-scanner/src/client_gen.rs
- wayland-scanner/tests/scanner_assets/test-client-code.rs
- wayland-tests/tests/attach_to_surface.rs
- wayland-tests/tests/client_bad_requests.rs
- wayland-tests/tests/client_proxies.rs
- wayland-tests/tests/destructors.rs
- wayland-tests/tests/globals.rs
- wayland-tests/tests/helpers/mod.rs
- wayland-tests/tests/protocol_errors.rs
- wayland-tests/tests/server_clients.rs
- wayland-tests/tests/server_created_object.rs
- wayland-tests/tests/server_global_filter.rs
- wayland-tests/tests/server_resources.rs
- wayland-tests/tests/xdg_shell_ping.rs
This promotes the `UserData` associated type to a full generic parameter (on the client only).
> Promote client dispatch data

- wayland-server/src/lib.rs
Allows to re-implement things like smithay's [`keyboard::has_focus`](https://github.com/Smithay/smithay/blob/f061ced7aa3366df091ab2b8af03d1730fb967fa/src/wayland/seat/keyboard/mod.rs#L503-L516) on 0.30.
> server: Allow to receive `ClientId` from `Resource`

- wayland-protocols-misc/CHANGELOG.md
- wayland-protocols-misc/protocols/virtual-keyboard-unstable-v1.xml
- wayland-protocols-misc/src/lib.rs
[`virtual_keyboard_unstable_v1` protocol][1] provides an application with requests which emulate the behavior of a physical keyboard. I'm not sure how up-to-date this is, but there is a table which lists clients and compositors with the input protocols they support at which version ([view here][2]). There is [an MR to add the protocol to `wayland-protocols`][3], but my only hesitancy is that there is a note that work is ["Stalled because of use case is not clear and technically a virtual seat might be preferred"][4]. In any case, I created this PR because adding this protocol here would replace the [`zwp-virtual-keyboard` crate][5], and any other one-off implementations.
I also cleaned up some formatting 😊 
[1]: https://gitlab.freedesktop.org/wlroots/wlroots/-/blob/e279266f714c7122e9ad97d5 …
> protocols: introduce misc/virtual-keyboard-unstable-v1

- wayland-protocols/src/lib.rs
Users of releases prior to 0.30.0 won't expect these protocols to be split into their own crates.
This will make it easier for them to find the protocols they are looking for.
> Link to wlr, plasma and misc protocols in the wayland_protocol docs

- wayland-backend/CHANGELOG.md
- wayland-backend/src/sys/server_impl/mod.rs
locking the state when invoking the pending
destructors can lead to deadlocks if a
destructor tries to send an event
> backend: do not lock state on destruction

- wayland-backend/CHANGELOG.md
- wayland-backend/src/sys/server_impl/mod.rs
the previous fix did not properly release the lock before calling the pending destructors
> backend: fix state lock release

- wayland-backend/Cargo.toml
Since wayland-rs depends on 1.53, union, const_generics and const_new may be enabled.
> backend: enable some smallvec features

- wayland-client/CHANGELOG.md
- wayland-client/examples/list_globals.rs
- wayland-client/examples/simple_window.rs
- wayland-client/src/event_queue.rs
- wayland-client/src/lib.rs
- wayland-server/CHANGELOG.md
- wayland-server/src/dispatch.rs
- wayland-server/src/global.rs
- wayland-server/src/lib.rs
- wayland-tests/tests/attach_to_surface.rs
- wayland-tests/tests/client_connect_to_env.rs
- wayland-tests/tests/client_connect_to_socket.rs
- wayland-tests/tests/client_proxies.rs
- wayland-tests/tests/destructors.rs
- wayland-tests/tests/helpers/globals.rs
- wayland-tests/tests/helpers/mod.rs
- wayland-tests/tests/server_clients.rs
- wayland-tests/tests/server_created_object.rs
- wayland-tests/tests/server_global_filter.rs
- wayland-tests/tests/server_resources.rs
- wayland-tests/tests/xdg_shell_ping.rs
This reworks the `Dispatch` traits on both client and server side to have a generic third parameter, essentially making them identical to the `DelegateDispatch` trait, which is now removed.
That third type parameter has a default value `=Self`, meaning that its usage for end user is almost unaffected. For provides of `DelegateDispatch` impls, the update is essentially a `s/DelegateDispatch/Dispatch/`.
**Pros:** Makes the whole thing simpler as there is only a single trait now.
**Cons:** `Dispatch` is now slightly less convenient to manually implement at the end of the chain, as you must write `state: &mut Self` instead of `&mut self` in the method prototype. Though that is largely mitigated by the fact that most implementations are done using macros.
> client/server: fuse DelegateDispatch into Dispatch

- wayland-backend/CHANGELOG.md
- wayland-backend/src/protocol.rs
- wayland-backend/src/rs/client_impl/mod.rs
- wayland-backend/src/rs/server_impl/client.rs
- wayland-backend/src/rs/server_impl/registry.rs
- wayland-backend/src/rs/socket.rs
- wayland-backend/src/rs/wire.rs
- wayland-backend/src/sys/client_impl/mod.rs
- wayland-backend/src/sys/server_impl/mod.rs
- wayland-backend/src/test/destructors.rs
- wayland-backend/src/test/many_args.rs
- wayland-backend/src/test/object_args.rs
- wayland-backend/src/test/protocol_error.rs
- wayland-backend/src/test/server_created_objects.rs
- wayland-scanner/src/common.rs
- wayland-scanner/tests/scanner_assets/test-client-code.rs
- wayland-scanner/tests/scanner_assets/test-server-code.rs
A `NULL` value in a nullable string is distict from an empty non-`NULL` string. So this changes `Argument::Str` to contain an `Option`, updates `sys` to match how this is represented in libwayland (as a `NULL` pointer), updates `rs` to match the wire protocol for this, and fixes unit tests and `wayland-scanner` accordingly.
Fixes segfault when `NULL` was passed to `wl_data_offer::accept` with the `sys` backend.
I was going to make changes for nullable arrays too, but those appear to be broken in libwayland as well, so that can stay as is for now. (https://gitlab.freedesktop.org/wayland/wayland/-/issues/306)
> backend/scanner: Fix handling of nullable strings

- wayland-client/src/event_queue.rs
- wayland-scanner/src/common.rs
- wayland-scanner/src/server_gen.rs
- wayland-scanner/tests/scanner_assets/test-client-code.rs
- wayland-scanner/tests/scanner_assets/test-server-code.rs
- wayland-tests/tests/server_created_object.rs
This also fixes the event_created_child macro to match a `pat` to allow paths and expressions to work.
> scanner: change OPCODE constants to u16

- wayland-backend/src/client_api.rs
- wayland-client/src/event_queue.rs
- wayland-scanner/src/client_gen.rs
- wayland-scanner/tests/scanner_assets/test-client-code.rs
This allows using `Proxy::data` on custom `ObjectData` implementations, and simplifies the implementation of QueueProxyData.
> Improve user data support in ObjectData

- wayland-backend/CHANGELOG.md
- wayland-backend/src/server_api.rs
- wayland-backend/src/test/destructors.rs
- wayland-backend/src/test/many_args.rs
- wayland-backend/src/test/mod.rs
- wayland-backend/src/test/object_args.rs
- wayland-backend/src/test/protocol_error.rs
- wayland-backend/src/test/server_created_objects.rs
- wayland-backend/src/test/sync.rs
For smithay compositors it is completely optional to implement the
ClientData trait, however due to the required functions on the trait it
is still quite verbose to just implement some dummy struct to use for
it.
Both Smallvill and Anvil have this implemented on a NOOP struct, which
indicates that the majority of compositors will likely not interested in
implementing this themselves.
To make things a little easier for people not interested in implementing
this, a default implementation for `()` is added in this patch. This
allows just passing `Arc::new(())` to `insert_client`.
For people interested in actually using this trait, all functions have
been mode optional. That way it's going to be much cleaner when
compositors just want to provide a partial implementation.
> Simplify ClientData implementation

- wayland-client/CHANGELOG.md
- wayland-client/src/conn.rs
- wayland-client/src/event_queue.rs
- wayland-client/src/lib.rs
This also fixes some potential missed wakeups when using EventQueue methods in a multi-threaded application.
> client: Add FreezeHandle

- wayland-client/src/lib.rs
- wayland-server/src/lib.rs
The code generated by the scanner already meets these bounds, adding
them to the trait simplifies generic code using them.
Fixes #533
> Add Clone+Debug bounds to Proxy and Resource

- wayland-backend/CHANGELOG.md
- wayland-backend/src/rs/socket.rs
If writing a message fails because the buffer is full and cannot be
flushed, this means that the other end is unresponsive, and thus fatal
to the connection.
Fixes #522
> backend: don't do blocking flushes

- wayland-client/src/lib.rs
- wayland-server/src/lib.rs
Adds `Eq` and `Hash` impls for `Weak` so that it can be used as the key in a `HashMap`
> client/server: Eq and Hash for Weak helpers

- wayland-server/CHANGELOG.md
- wayland-server/src/lib.rs
replaces `Resource::client_id()` with `Resource::client()` directly returning the owning `Client` instead of the internal `ClientId`
> server: directly return client instead of client id

- wayland-protocols/CHANGELOG.md
- wayland-protocols/src/ext.rs
- wayland-protocols/src/lib.rs
- wayland-protocols/src/wp.rs
- wayland-protocols/src/xwayland.rs
Since there are now two xwayland protocols, there is now an `xwayland` module for this protocols.
~~Pending on a new wayland-protocols release with https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/174~~
> Update wayland-protocols to 1.29

- wayland-protocols/CHANGELOG.md
- wayland-protocols/src/wp.rs
Adds support for `tearing-control-v1`.
> Bump wayland-protocols to 1.30

- wayland-protocols-wlr/CHANGELOG.md
`cargo clippy --all --all-features --all-targets -- -D warnings` exited without errors/warnings and `cargo doc --all-features` build the docs with the new pages.
> Update wlr-protocols submodule

- wayland-backend/CHANGELOG.md
- wayland-backend/src/rs/wire.rs
This allows the higher level code to try reading again to get any remaining bytes of the message, instead of treating the message as malformed.
This matches the implementation of `queue_event()` in libwayland which returns `0` in this case (rather than `-1` for an error).
> backend: Return `MissingData` instead of `Malformed` if `len > raw.len()`

- wayland-sys/CHANGELOG.md
- wayland-sys/src/server.rs
`&mut (*data).listener` creates a reference only valid for the listener field according to stacked borrows. Later attempting to get access to the entire container is UB. Using `addr_of_mut!()` avoids the intermediate reference, avoiding UB.
> Fix UB in rust_listener_create

- deny.toml
When I tried to introduce `calloop` as an optional dependency the CI failed at the cargo-deny action. One of calloops dependencies uses the Zlib license. This PR is adding it to the allow list of cargo-deny.
> Add Zlib to cargo-deny license allow list

- wayland-client/CHANGELOG.md
- wayland-client/Cargo.toml
- wayland-client/src/calloop.rs
- wayland-client/src/lib.rs
I have added the `WaylandSource` struct from sctk to the wayland-client crate.
It can be enabled with the `calloop` feature flag.
I also wrote a little description for the feature in `src/lib.rs`.
> Add WaylandSource behind the `calloop` cargo feature

- wayland-client/Cargo.toml
- wayland-cursor/Cargo.toml
- wayland-egl/Cargo.toml
- wayland-scanner/Cargo.toml
- wayland-server/Cargo.toml
- wayland-sys/Cargo.toml
Not all crates were build with all features enabled for docs.rs. So some of the hyperlinks broke.
This adds
```toml
[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
```
to the Cargo.toml of all wayland-rs crates except the `wayland-tests` crate.
> Build documentation with all features for docs.rs

- wayland-backend/Cargo.toml
- wayland-backend/src/lib.rs
- wayland-backend/src/sys/mod.rs
This makes using wayland-backend within the raw-window-handle ecosystem easier. A new `raw-window-handle` feature has been added to enable this trait implementation
> backend: implement HasRawDisplayHandle for Backend in sys

- wayland-backend/src/lib.rs
- wayland-backend/src/sys/mod.rs
- wayland-client/src/lib.rs
- wayland-server/src/lib.rs
- wayland-sys/src/lib.rs
The wayland-protocols crates already had these enabled.
Related to this is #587 which sets `--cfg=docsrs` in the crates where it has not been done yet for docs.rs
> Enable doc_auto_cfg in crates with features

- wayland-server/Cargo.toml
- wayland-server/src/socket.rs
It looks like the only other `AsRawFd` implementations here are in wayland-backend and already have corresponding `AsFd` implementations.
> server: Implement `AsFd` for `ListeningSocket`

- README.md
- wayland-backend/Cargo.toml
- wayland-client/Cargo.toml
- wayland-cursor/Cargo.toml
- wayland-egl/Cargo.toml
- wayland-protocols-misc/Cargo.toml
- wayland-protocols-plasma/Cargo.toml
- wayland-protocols-wlr/Cargo.toml
- wayland-protocols/Cargo.toml
- wayland-scanner/Cargo.toml
- wayland-server/Cargo.toml
- wayland-sys/Cargo.toml
- wayland-tests/Cargo.toml
Updates the MSRV in the Readme and also defines the `rust-version` in the crate manifests
> Reflect MSRV in Readme

- wayland-backend/src/protocol.rs
- wayland-client/Cargo.toml
- wayland-client/src/conn.rs
- wayland-client/src/globals.rs
- wayland-client/src/lib.rs
- wayland-egl/Cargo.toml
- wayland-egl/src/lib.rs
- wayland-scanner/Cargo.toml
- wayland-scanner/src/common.rs
- wayland-scanner/src/lib.rs
- wayland-scanner/src/token.rs
- wayland-scanner/tests/scanner_assets/test-client-code.rs
- wayland-scanner/tests/scanner_assets/test-server-code.rs
- wayland-server/Cargo.toml
- wayland-server/src/lib.rs
- wayland-server/src/socket.rs
The commits are mostly independent, so if you think any of the commits is bad for maintainability, I can easily drop it. The commits I'm most confident about are:
* https://github.com/Smithay/wayland-rs/commit/49779784766a15d937b098289124d4aaffb754b5 "Remove futures dependencies from wayland-client"
* https://github.com/Smithay/wayland-rs/commit/84aad31150043622a5ffd42c9c9a71ec96e2d98f "Reduce code bloat of smallvec![] macro"
> Reduce compile time

- wayland-client/src/calloop.rs
This should use `eprintln!` when the log
feature is not present with `calloop`.
> wayland-client: fix compilation without `log`

- wayland-scanner/CHANGELOG.md
- wayland-scanner/src/client_gen.rs
- wayland-scanner/src/server_gen.rs
- wayland-scanner/tests/scanner_assets/test-client-code.rs
- wayland-scanner/tests/scanner_assets/test-server-code.rs
Sometimes it may be nessecary to store a `HashMap<ObjectId, T>` or a `HashSet<ObjectId>`. HashMap::get(_mut) allows using a generic parameter which implements `Borrow<K>`. By implementing Borrow<ObjectId> on the types wayland-scanner generates, a HashMap lookup can directly use `HashMap::get` with the protocol object wrapper instead of needing to call `.id()` and then use the id for lookup.
Resolves #600
> scanner: implement Borrow<ObjectId>

- wayland-protocols-plasma/CHANGELOG.md
- wayland-protocols-plasma/src/lib.rs
The protocol was fixed by https://github.com/KDE/plasma-wayland-protocols/commit/b00501d7cdf7c4107af03ca29cb14fc0d21c5b3e which seems to be working alright with wayland-scanner locally.
> Uncomment Plasma window management protocol

- wayland-client/CHANGELOG.md
- wayland-client/wayland.xml
- wayland-server/CHANGELOG.md
- wayland-server/wayland.xml
I think the most noteworthy change here is probably the addition of `preferred_scale`, which I think makes some sense to integrate considering fractional scale is already supported and implementing preferred scale on top of that should be pretty simple for compositors.
> Update wayland.xml to 1.21.92

- wayland-sys/src/client.rs
- wayland-sys/src/cursor.rs
- wayland-sys/src/egl.rs
- wayland-sys/src/server.rs
The standard practice for loading dynamic libraries is to use `sonames`, versioned `.so` files. That way you ensure that the `.so` file contains the expected API, and not another version with possibly breaking changes. Therefore, the soname version should be tried first, and only then as a backup the unversioned `.so` file.
Doing so is not a workaround for Ubuntu, like the comments suggest, virtually all Linux distributions use sonames, so those comments have also been removed.
For me this order caused problems when making a Snap package for Neovide, using the classic confinement. On Ubuntu and also in Snaps, the unversioned `.so` file is only installed if you install the developer packages, so the Snap does not include those. Therefore the `.so` file is not found and loaded from the host …
> Prefer sonames when loading dynamic libraries

- wayland-protocols/src/ext.rs
- wayland-protocols/src/wp.rs
This relies on unreleased (but already merged) changes upstream. I'm not sure if you'd rather merge this now or wait for an upstream release, but I'm sharing this at this point since I want to write application code that uses this protocol.
> Update wayland-protocols to 1.32

- wayland-client/CHANGELOG.md
- wayland-client/Cargo.toml
- wayland-protocols-misc/CHANGELOG.md
- wayland-protocols-misc/Cargo.toml
- wayland-protocols-plasma/CHANGELOG.md
- wayland-protocols-plasma/Cargo.toml
- wayland-protocols-wlr/CHANGELOG.md
- wayland-protocols-wlr/Cargo.toml
- wayland-protocols/CHANGELOG.md
- wayland-protocols/Cargo.toml
- wayland-scanner/CHANGELOG.md
- wayland-scanner/src/common.rs
- wayland-server/CHANGELOG.md
- wayland-server/Cargo.toml
Changelog: https://github.com/bitflags/bitflags/blob/2.0.0/CHANGELOG.md#200.
This is a breaking change. The API that is implemented by the macro is now different.
We didn't really have to derive anything apart from `Debug` to make it work, but considering this is public I derived all other traits as well except `PartialOrd`, `Ord` and `Default`.
Fixes #622.
> Bump `bitflags` to v2

- wayland-server/CHANGELOG.md
- wayland-server/src/socket.rs
Fixes a race condition that can happen if one thread unlinks the .lock between our open() and flock() calls.
> server: Verify that .lock fd matches on-disk file

- wayland-backend/CHANGELOG.md
- wayland-backend/src/rs/server_impl/handle.rs
- wayland-backend/src/server_api.rs
- wayland-backend/src/sys/server_impl/mod.rs
- wayland-server/CHANGELOG.md
- wayland-server/src/display.rs
This makes it easy to use `wayland_server::Display` with `calloop` 0.11 without hacking around IO safety.
If these solutions don't seem ideal for any reason, there may be alternatives. But some change is needed.
> server: Add `flush` to `DisplayHandle`, and implement `AsFd` for `Display`, for use in smithay

- wayland-backend/CHANGELOG.md
- wayland-backend/src/client_api.rs
- wayland-backend/src/rs/client_impl/mod.rs
- wayland-backend/src/sys/client_impl/mod.rs
- wayland-client/CHANGELOG.md
- wayland-client/src/conn.rs
- wayland-client/src/event_queue.rs
- wayland-tests/tests/helpers/mod.rs
This should fix the multithreading issues that have been encountered.
cc @kchibisov
> backend: fix prepare_read behavior

- wayland-backend/CHANGELOG.md
- wayland-backend/src/rs/server_impl/common_poll.rs
- wayland-backend/src/rs/server_impl/handle.rs
- wayland-backend/src/rs/server_impl/mod.rs
- wayland-backend/src/server_api.rs
- wayland-backend/src/sys/server_impl/mod.rs
- wayland-backend/src/test/destructors.rs
- wayland-backend/src/test/many_args.rs
- wayland-backend/src/test/mod.rs
- wayland-backend/src/test/object_args.rs
- wayland-backend/src/test/protocol_error.rs
- wayland-server/CHANGELOG.md
- wayland-server/src/dispatch.rs
- wayland-server/src/global.rs
- wayland-tests/tests/destructors.rs
> server: allow accessing resource in `Dispatch::destroyed`

- wayland-backend/CHANGELOG.md
- wayland-backend/src/rs/server_impl/client.rs
> backend: fix server-side WAYLAND_DEBUG

- wayland-backend/CHANGELOG.md
- wayland-backend/src/client_api.rs
- wayland-backend/src/rs/client_impl/mod.rs
- wayland-backend/src/sys/client_impl/mod.rs
- wayland-client/CHANGELOG.md
- wayland-client/src/conn.rs
- wayland-client/src/event_queue.rs
This helps for using an `Generic<EventQueue>` with calloop 0.11.
https://github.com/Smithay/wayland-rs/pull/635 added this server-side for use in Smithay; the same thing seems useful for sctk.
> client: Implement `AsFd` for `Connection` and `EventQueue`

- wayland-client/examples/simple_window.rs
We need to handle or ignore events from `wl_shm` and `wl_surface`, since the server does in fact produce events for those.
> Fix crash in `simple_window` example

- wayland-scanner/CHANGELOG.md
- wayland-scanner/src/common.rs
- wayland-scanner/tests/scanner_assets/test-client-code.rs
- wayland-scanner/tests/scanner_assets/test-server-code.rs
I thought there was an empty type in the standard library, but somehow couldn't find it when I implemented this.
This makes it a bit more explicit that the variant is never constructed, and should help a bit with optimization. It does not impact public API.
> scanner: Use `std::convert::Infallible` in `__phantom_lifetime` variants

- wayland-backend/Cargo.toml
- wayland-backend/src/rs/server_impl/client.rs
- wayland-backend/src/rs/server_impl/common_poll.rs
- wayland-backend/src/rs/server_impl/handle.rs
- wayland-backend/src/rs/socket.rs
- wayland-backend/src/sys/client_impl/mod.rs
- wayland-backend/src/test/many_args.rs
- wayland-backend/src/types/server.rs
- wayland-client/Cargo.toml
- wayland-client/src/conn.rs
- wayland-client/src/event_queue.rs
- wayland-cursor/Cargo.toml
- wayland-cursor/src/lib.rs
- wayland-server/Cargo.toml
- wayland-server/src/socket.rs
https://github.com/Smithay/wayland-rs/issues/653
Incomplete. Looks like `rustix` needs support for `SO_PEERCRED`.
> Port from nix to rustix

- wayland-backend/src/rs/socket.rs
This should fix the failing FreeBSD CI test, and behave correctly. This is perhaps better, though I think either *should* work (https://github.com/bytecodealliance/rustix/issues/914).
The other `sendmsg`/`recvmsg` calls use `rustix::cmsg_space!`, and should work without issue.
> Use `send` instead of `sendmsg` to send with no fds

- wayland-backend/src/rs/server_impl/mod.rs
This should fix the failing `check-minimal` CI test.
> Fix `unused-imports` warning on recently `nightly`

- wayland-backend/src/debug.rs
- wayland-backend/src/lib.rs
- wayland-backend/src/rs/client_impl/mod.rs
- wayland-backend/src/rs/mod.rs
- wayland-backend/src/rs/server_impl/client.rs
- wayland-backend/src/rs/server_impl/mod.rs
- wayland-backend/src/sys/client_impl/mod.rs
To make it possible to understand that something got discarded, print a message saying so inside when `WAYLAND_DEBUG` is enabled.
This also changes how timestamps are computed for `WAYLAND_DEBUG` log so they align with `libwayland-client` to look into logs using both at the same time more accessible. The `[rs]` particle was added to the log to give a hint which library was used, which could be helpful when looking into random logs.
> Log requests on dead objects

- wayland-backend/src/rs/socket.rs
- wayland-backend/src/rs/wire.rs
This avoids some awkward and potentially error-prone code, and should perform no worse than how the `Buffer` type was used.
> Use `VecDeque<OwnedFd>` and `Vec<OwnedFd>` for `in_fds`/`out_fds`

- wayland-backend/src/rs/socket.rs
- wayland-backend/src/rs/wire.rs
I don't think `sendmsg`/`recvmsg` are necessarily guaranteed to read/write a multiple of 4 bytes, so for correctness we need to buffer bytes rather than words. This also avoids unsafe casts.
This is based on https://github.com/Smithay/wayland-rs/pull/666. Not sure if the helpers here for reading/writing words to the buffer could be improved. Perhaps as methods of `Buffer`, if that's only being used for this.
This doesn't seem particularly worse to handle than the previous way, since either version has to deal with lengths in bytes vs. words, and array padding.
> backend: Use Buffer<u8> instead of Buffer<u32>

- .cirrus.yml
FreeBSD 12 is EOL, and the package archives don't seem to be available anymore.
> Remove FreeBSD 12.1 CI

- wayland-client/examples/simple_window.rs
Haven't tested on a big-endian system, but this should be correct.
It seems redundant to use bitshifts only to convert with `to_*_bytes`, so just use an array.
Fixes https://github.com/Smithay/wayland-rs/issues/385.
> client: Fix endianness in `simple_window` example

- wayland-backend/CHANGELOG.md
- wayland-backend/src/rs/socket.rs
This could be considered a breaking API change, but probably no callers are actually handling it. And it seems libwayland does this, so making the rs backend consistent here can be considered a bug fix.
> backend/rs: Retry send/recv on `EINTR`

- wayland-client/src/event_queue.rs
If dispatch_inner_queue dispatches some events, blocking_dispatch will still wait for some events to come in, rather than turning the loop again and checking its done variable. This is causing Alacritty 0.13 to hang on startup.
> Fix deadlock in blocking_dispatch

- wayland-backend/src/rs/client_impl/mod.rs
- wayland-backend/src/rs/wire.rs
- wayland-backend/src/sys/client_impl/mod.rs
- wayland-backend/src/sys/server_impl/mod.rs
- wayland-backend/tests/rs_sys_impls.rs
- wayland-scanner/CHANGELOG.md
- wayland-scanner/src/c_interfaces.rs
- wayland-scanner/tests/scanner_assets/test-interfaces.rs
- wayland-server/src/socket.rs
`static mut` is generally best avoided. It seems to only be necessary currently to allow the use of non-`Sync` types, since pointers are not sync.
This also removes the `NULLPTR` constant in favor of using `std::ptr::null`, uses `.as_ptr()` instead of casting, and uses the arrray repeating syntax to define `types_null`. None of those should impact behavior or the public API.
`*_requests` and `*_events` static are no longer public now. This is theoretically a breaking change, but shouldn't really impact anything.
> Use a wrapper type implementing `Sync`, instead of `static mut`

- wayland-protocols/CHANGELOG.md
- wayland-protocols/src/wp.rs
- wayland-protocols/src/xdg.rs
> Update `wayland-protocols` to 1.34

- wayland-client/examples/list_globals_no_dispatch.rs
- wayland-client/src/lib.rs
Also mention ObjectData in the docs for bypassing Dispatch.
> wayland-client: add example for bypassing Dispatch

- wayland-cursor/src/lib.rs
I want to add a way to load cursor from raw data
> feat: load cursor from data

- wayland-backend/build.rs
- wayland-client/build.rs
The lastest Rust nightly [adds checking for cfgs] and their possible values.  This requires us to define via `build.rs` that `coverage` is a valid `cfg`, and that it is a "boolean" without any allowed values.
[adds checking for cfgs]: https://blog.rust-lang.org/2024/05/06/check-cfg.html
> Configure new `check-cfg` lint that `coverage` is an allowed option

- wayland-backend/src/server_api.rs
- wayland-scanner/src/server_gen.rs
- wayland-scanner/tests/scanner_assets/test-server-code.rs
- wayland-server/CHANGELOG.md
- wayland-server/src/lib.rs
In `smithay` we quite extensively use `Weak` as the key for caching some other resource. Cleaning up these resources
often requires checking if the key is still alive. Without an explicit function to check `Weak` for alive we have to resort to `Weak::upgrade().is_ok()`. An explicit function can save us from actually upgrading the resource itself, saving us quite some cpu time.
> wayland-server: alive check for Weak

- wayland-protocols/CHANGELOG.md
Due to https://gitlab.freedesktop.org/wayland/wayland-protocols/-/commit/1c57b24ff867eabacb6ecc1e74b1e4d1ccafcf4b, the generated code here is now an enum instead of a `u32`.
It seems reasonable to make this a breaking change for `wayland-protocols-*`, but not release a semver bump of `wayland-client`/`wayland-server`.
> protocols: Mention breaking API change

- wayland-backend/CHANGELOG.md
- wayland-backend/Cargo.toml
- wayland-backend/src/lib.rs
- wayland-backend/src/protocol.rs
- wayland-backend/src/sys/mod.rs
Includes https://github.com/Smithay/wayland-rs/pull/707 (rebased and with formatting fix) and https://github.com/Smithay/wayland-rs/pull/712, as well as changelog entries. (And a dev dependency bump.)
Want to get these merged before a release. Creating a PR mainly to verify CI passes.
> Updates for next release

- wayland-backend/CHANGELOG.md
- wayland-backend/Cargo.toml
- wayland-client/Cargo.toml
- wayland-cursor/Cargo.toml
- wayland-egl/Cargo.toml
- wayland-protocols-misc/CHANGELOG.md
- wayland-protocols-misc/Cargo.toml
- wayland-protocols-plasma/CHANGELOG.md
- wayland-protocols-plasma/Cargo.toml
- wayland-protocols-wlr/CHANGELOG.md
- wayland-protocols-wlr/Cargo.toml
- wayland-protocols/CHANGELOG.md
- wayland-protocols/Cargo.toml
- wayland-scanner/CHANGELOG.md
- wayland-scanner/Cargo.toml
- wayland-server/CHANGELOG.md
- wayland-server/Cargo.toml
- wayland-sys/Cargo.toml
`cargo release --no-publish --no-tag --no-push --execute patch`
`wayland-protocols` needed a breaking version bump, so it was manually changed. The `CHANGELOG.md` files also had to be updated manually.
If CI is happy, hopefully tagging a release will automatically release everything fine.
> Bump versions and update changelogs

- wayland-backend/CHANGELOG.md
- wayland-backend/src/rs/server_impl/common_poll.rs
I am not sure, if we need to do the same thing here for kqueue, I only observed this problem on an epoll system, but I figured it can't hurt.
This fixes a deadlock from killed clients blocking the loop in `dispatch_all_clients` for the rust-backend.
> backend: delete dead clients from epoll

- wayland-backend/CHANGELOG.md
- wayland-backend/src/sys/client_impl/mod.rs
some drivers seem to unconditionally dispatch
the default event queue. this can lead to spurious dispatching of wayland-rs managed objects breaking the tls invariant.
prevent this from happening by moving everything
off the default event queue to a distinct event queue
> backend: use distinct event queue for client sys

- wayland-protocols-wlr/README.md
The repository URL in the README still pointed to the old GitHub repository.
> Update wlr-protocols URL in README

- wayland-protocols/CHANGELOG.md
- wayland-protocols/src/ext.rs
- wayland-protocols/src/xdg.rs
`xdg-toplevel-icon-v1`, `ext-image-capture-source-v1`, `ext-image-copy-capture-v1`.
Pending upstream tagged release.
> Bump wayland-protocols to 1.37

- wayland-backend/CHANGELOG.md
- wayland-backend/src/sys/client_impl/mod.rs
fixes a regression introduced in e777e85f6846ee732ab33adce5755bfc57b08649 which moved all proxies to a separate event queue but left proxies imported with `Backend::manage_object` on the default queue.
cc @chrisduerr
> backend/sys: associate imported proxy with correct event queue

- wayland-scanner/src/parse.rs
Currently wayland-scanner only allows the `<?xml ... ?>` declaration and the protocol tag at the start of a xml protocol definition. This PR allows one to additionaly specify a `<!DOCTYPE ...>` like this:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE protocol SYSTEM "https://gitlab.freedesktop.org/wayland/wayland/-/raw/ee12e69b8fb8c55460126e4e527eb4f7fee5526e/protocol/wayland.dtd">
<protocol name="test_proto">
<interface name="test_interface" version="1">
<description summary="Testing"></description>
<event name="ping"></event>
</interface>
</protocol>
```
The specified file can be consumed by LSPs to enable assisting with autocompletion and syntax checking.
> Allow DOCTYPE in protocol definition

- wayland-client/CHANGELOG.md
- wayland-client/Cargo.toml
- wayland-cursor/Cargo.toml
- wayland-protocols-misc/Cargo.toml
- wayland-protocols-plasma/Cargo.toml
- wayland-protocols-wlr/Cargo.toml
- wayland-protocols/CHANGELOG.md
- wayland-protocols/Cargo.toml
- wayland-server/CHANGELOG.md
- wayland-server/Cargo.toml
- wayland-tests/Cargo.toml
`cargo release --no-publish --no-tag --no-push --execute patch --prev-tag-name release-2024-09-04 --exclude wayland-sys --exclude wayland-backend --exclude wayland-scanner --exclude wayland-egl`
If on `master` with `prev-tag-name` specified, the unchanged crates produce warnings, but are not automatically excluded. Not sure if there's some way to do that.
> chore: Release

- deny.toml
- wayland-backend/CHANGELOG.md
- wayland-backend/src/debug.rs
- wayland-backend/src/rs/server_impl/client.rs
- wayland-backend/src/rs/server_impl/handle.rs
- wayland-backend/src/rs/server_impl/registry.rs
- wayland-client/src/event_queue.rs
- wayland-server/src/dispatch.rs
- wayland-sys/src/server.rs
delay client cleanup until the state lock is dropped to prevent potential deadlocks in drop impls of the client state.
> backend/rs: delay client cleanup

- wayland-backend/Cargo.toml
- wayland-backend/src/rs/socket.rs
The stack size is 152 bytes which is teeny.
> Remove a pointless allocation

- wayland-backend/Cargo.toml
Since aa8607e moved scoped-tls to an optional dependency,
`cargo test -p wayland-backend` fails to build (independent from #782)
since neither the client_system nor server_system features are enabled:
error[E0432]: unresolved import `scoped_tls`
--> wayland-backend/src/sys/client_impl/mod.rs:26:5
|
26 | use scoped_tls::scoped_thread_local;
|     ^^^^^^^^^^ use of undeclared crate or module `scoped_tls`
error[E0432]: unresolved import `scoped_tls`
--> wayland-backend/src/sys/server_impl/mod.rs:20:5
|
20 | use scoped_tls::scoped_thread_local;
|     ^^^^^^^^^^ use of undeclared crate or module `scoped_tls`
error[E0425]: cannot find value `BACKEND` in this scope
--> wayland-backend/src/sys/client_impl/mod.rs:378:19
|
378 |         let ret = BACKEND.set(&backend, || unsafe {
| …
> backend: Add scoped-tls as a dev-dependency

- wayland-backend/src/sys/mod.rs
Import `ObjectData` and `ObjectId` from submodule instead of `crate::client` so they'll be the `sys` variants regardless of compile options.
Fixes https://github.com/Smithay/wayland-rs/issues/782.
> backend/sys: Fix import for `cargo test` without `client_system`

- wayland-protocols-plasma/CHANGELOG.md
- wayland-protocols-plasma/src/lib.rs
Some protocols have [added a warning](https://invent.kde.org/libraries/plasma-wayland-protocols/-/merge_requests/80):
```
Warning! The protocol described in this file is a desktop environment
implementation detail. Regular clients must not use this protocol.
Backward incompatible changes may be added without bumping the major
version of the extension.
```
While protocols like `blur` presumably are considered safe to use.
Perhaps we should have a feature flag for those "implementation detail" protocols. But for now, this is just an update without breaking anything.
> protocols-plasma: Update to `plasma-wayland-protocols` 1.16.0

- wayland-client/src/event_queue.rs
This fixes a typo and includes a description of the `@<>` syntax which allows delegatng over a generic type.
I needed this feature but it wasn't documented, so I was lucky to catch a dev and asked. With this description, even unlucky people can find this feature.
> Update delegate_dispatch docs

- wayland-backend/CHANGELOG.md
- wayland-backend/src/sys/client_impl/mod.rs
Don't allow calling `send_request` while we have dispatch_pending, since `send_request` can call `wl_proxy_add_dispatcher`, which requires user to synchronize access to it.
Otherwise the proxy might be created by `send_request` but then get a `null` deref if dispatch is called at the right time because the proxy data was not set.
> backend: hold the dispatch lock for send_request

- wayland-backend/src/rs/socket.rs
- wayland-tests/Cargo.toml
- wayland-tests/tests/backend_socket_out_limits.rs
backend/rs: do flush as multiple sendmsg if needed to enforce MAX_FDS_OUT limit
Fixes https://github.com/Smithay/wayland-rs/issues/806
> backend/rs: enforce MAX_FDS_OUT limit

- wayland-protocols/CHANGELOG.md
- wayland-protocols/src/ext.rs
- wayland-protocols/src/wp.rs
This PR adds support for the [`ext-background-effect`](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/commit/dac6393216d2755c0302d77e739eb1bd96156852) protocol.
> protocols: Update to wayland-protocols 1.45

- .github/workflows/ci.yml
- wayland-backend/build.rs
- wayland-backend/src/client_api.rs
- wayland-backend/src/debug.rs
- wayland-backend/src/lib.rs
- wayland-backend/src/protocol.rs
- wayland-backend/src/rs/client_impl/mod.rs
- wayland-backend/src/rs/server_impl/mod.rs
- wayland-backend/src/rs/wire.rs
- wayland-backend/src/server_api.rs
- wayland-backend/src/sys/client_impl/mod.rs
- wayland-backend/src/sys/server_impl/mod.rs
- wayland-backend/src/types/client.rs
- wayland-backend/src/types/server.rs
- wayland-client/build.rs
- wayland-client/src/event_queue.rs
- wayland-client/src/lib.rs
This PR prevents tools like `cargo-llvm-cov` from trying to enable nightly features on stable, while still allowing other downstream crates to use `cfg(coverage)` for other things when coverage tools set the attribute.
I've tested this locally in an internal repo that uses `wayland-client` via `wl-clipboard-rs` and it resolved the nightly feature compilation failures.
Once the coverage attribute stabilizes, and `wayland-rs` bumps its MSRV, this could be removed in favor of just `cfg(coverage)` again.
Resolves https://github.com/Smithay/wayland-rs/issues/717
> Guard unstable coverage flags behind independent cfg

- wayland-protocols/Cargo.toml
- wayland-protocols/src/wp.rs
This should be an improvement on https://github.com/Smithay/wayland-rs/pull/827, using wildcards, and also `!` rules to exclude a few XML files we don't need.
Looks like we also need to update the tablet v2 protocol to use the `stable/` XML file.
Reduces size of `.crate` package from 216K to 152K.
> protocols: Do not include all of `protocols/` submodule; and use stable tablet v2
